backend:
  name: github
  # change repo to your git repository url
  repo: aranscope/aran.site

media_folder: static/assets
public_folder: /assets

collections:
  - name: cv
    label: Curriculum Vitae
    files:
      - name: cv
        label: CV
        file: src/data/cv.json
        fields:
          - name: name
            label: Name
            widget: string
            required: true
          - name: biography
            label: Biography
            widget: text
            required: false
          - name: contactInfo
            label: Contact info
            widget: list
            fields:
              - name: contact
                label: Contact
                widget: string
                required: true
              - name: link
                label: Link
                widget: string
          - name: education
            label: education
            widget: list
            fields:
              - name: institution
                label: Institution
                widget: string
                required: true
              - name: visible
                label: Visible
                widget: boolean
                hint: Controls whether this is visible
              - name: qualification
                label: qualification
                widget: string
                required: true
              - name: grade
                label: Grade
                widget: string
                required: false
              - name: start_date
                label: Start date
                widget: date
                required: true
              - name: end_date
                label: End date
                widget: date
                required: false
          - name: jobs
            label: jobs
            singular_label: job
            widget: list
            fields:
              - name: company
                label: Company
                widget: string
                required: true
              - name: visible
                label: Visible
                widget: boolean
                hint: Controls whether this is visible
              - name: role
                label: Role
                widget: string
                required: true
              - name: start_date
                label: Start date
                widget: date
                required: true
              - name: end_date
                label: End date
                widget: date
                required: false
              - name: descriptionVisible
                label: Include description?
                widget: boolean
              - name: description
                label: Description
                widget: text
                required: false
              - name: key_points
                label: Key points
                widget: list
                field:
                  name: point
                  label: Point
                  widget: string
          - name: skills
            label: Skills
            singular_label: skill
            widget: list
            fields:
              - name: skill
                label: Skill
                widget: string
                required: true
              - name: visible
                label: Visible
                widget: boolean
                hint: Controls whether this is visible
          - name: projects
            label: Awards & Projects
            singular_label: project
            widget: list
            fields:
              - name: name
                label: Name
                widget: string
                required: true
              - name: visible
                label: Visible
                widget: boolean
                hint: Controls whether this is visible
              - name: date
                label: Date
                widget: object
                fields:
                  - name: date
                    label: Date
                    widget: date
                  - name: visible
                    label: Visible
                    widget: boolean
                    required: false
                required: false
              - name: description
                label: description
                widget: object
                fields:
                  - name: description
                    label: Description
                    widget: text
                  - name: visible
                    label: Visible
                    widget: boolean
                    required: false
